# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchzip,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_15,
  zstd,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_15 ];
      }
      ''
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      artifact =
        if unpack then
          fetchzip {
            inherit url hash;
            nativeBuildInputs = [ zstd ];
          }
        else
          fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash unpack;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash unpack;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "N-V-__8AAM-tPgFSsje3FI7iURLjDLSOquhtONinvYZp3AHh";
    path = fetchZigArtifact {
      name = "curl";
      url = "https://github.com/curl/curl/releases/download/curl-8_19_0/curl-8.19.0.tar.gz";
      hash = "sha256-KiwR20wSJpGqI7Q2O+/aG/2AF3C/6/QeHSHO5PKrD3E=";
      unpack = false;
    };
  }
  {
    name = "curl-0.5.1-P4tT4T4AAQAWgbb1Iwh00q9raBCW4ZphsAkFh2U5oQ6X";
    path = fetchZigArtifact {
      name = "curl";
      url = "https://github.com/jiacai2050/zig-curl/archive/refs/tags/v0.5.1.tar.gz";
      hash = "sha256-XQrpc4owq+IfcYEjvubtsYXv3Tkk0RKdwXPDUZdgiEY=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAFrtpQI1j9eOv7aN3lt3eH1TJfH4npAdRIrg2gGH";
    path = fetchZigArtifact {
      name = "mbedtls";
      url = "https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.6.0.tar.gz";
      hash = "sha256-MsUA5z7oeOGT59Zr9eTDT7QruWimyflIiqRmsW9vO/8=";
      unpack = false;
    };
  }
  {
    name = "zigcli-0.6.2-ORC7jKipBgACkx_85RKXdxjINMRxJts-AmSLXMJqR2Ji";
    path = fetchZigArtifact {
      name = "zigcli";
      url = "git+https://github.com/jiacai2050/zigcli.git#8edd28e5f8ee4317b770a2bbb61902a88832f37f";
      hash = "sha256-+++JKEMAsk0Wfu39wEhFyfUcUFQbG1HXNQu6sxvucA4=";
      unpack = true;
    };
  }
  {
    name = "zigpty-0.0.0-wfmENlDkAQC7XCLW8R5HLMiVubZjV3Brq1lcA_vATIIU";
    path = fetchZigArtifact {
      name = "zigpty";
      url = "git+https://github.com/pithings/zigpty.git#60a6002851bbe489ca48c3b1964be34d36e04173";
      hash = "sha256-Iw5ZwF3Zx0KT1tTBIHjnvfH4R+RIzJCRA/xvqYZ+LSA=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAJj_QgDBhU17TCtcvdjOZZPDfkvxrEAyZkc14VN8";
    path = fetchZigArtifact {
      name = "zlib";
      url = "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz";
      hash = "sha256-mpOyt9/ax3zrpaVYpYDnRmfdb+3kWFuR7vtg8Dty3yM=";
      unpack = false;
    };
  }
]
