on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  tests:
    name: Run now tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install Nix
        uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
        with:
          add-channel: "true"
      - name: Run now
        env:
          BUILDERS: 'ssh://localhost - - 1 1 now now -'
        run: |
          nix run . -- run test
